# Generated by Django 4.2.4 on 2023-08-31 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(blank=True, max_length=100, null=True, verbose_name='content')),
                ('slug', models.CharField(max_length=50, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modification date')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
