# Generated by Django 4.2.4 on 2023-08-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_options_remove_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.CharField(verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_date',
            field=models.DateTimeField(verbose_name='дата изменения'),
        ),
    ]
