# Generated by Django 4.2.4 on 2023-08-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='названиеназвание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата изменения'),
        ),
    ]
