# Generated by Django 4.2.4 on 2023-08-28 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_product_create_date_alter_product_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата изменения'),
        ),
    ]
