# Generated by Django 4.2.4 on 2023-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_product_image_alter_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='max 100 chars', max_length=100, unique=True, verbose_name='наименование'),
        ),
    ]
