# Generated by Django 4.2.4 on 2023-09-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия_продукт', 'verbose_name_plural': 'Версия_продукты'},
        ),
    ]
